### ISSUE TITLE
Team up?

### ISSUE THREAD

**Issue by billiegoose** [gko/beautify#3]
I'm developing a tool also called [*beautify*](//github.com/wmhilton/beautify) and it seems pretty similar to yours. For instance, I'm using `prettier` for formatting the JS, and I see you even have switching to prettier as your issue #2, so we might be of similar mind. Since you have the coveted name on the npm registry, I thought I'd ask if you were interested in combining efforts? Your tool is ahead of mine in JSON and XML support. I think mine is ahead in supporting glob patterns and file extensions to beautify multiple files at once. I'm also planning on adding a PHP beautifier.

**Comment by CTimmerman** [comment]
I though https://github.com/beautify-web/js-beautify was the first. It even has a nice webpage demo at https://beautifier.io/
